compatibility for Typo3 11
DMKEBUSINESSGMBH/mkvarnish pull request #6
Opened 2022-04-29 08:24 UTC by pwagner85

2022-04-29 10:00 UTC, rengaw83 requested changes

2022-04-29 10:00 UTC, rengaw83 commented on Classes/Cache/VarnishBackend.php
> +     * @return array|null
we only support php 7.4 and above? than we should use return types and strict types.

2022-04-29 10:00 UTC, rengaw83 commented on Classes/Middleware/SetVarnishHeadersMiddleware.php
> + * @author Philipp Wagner
:'(
please add a new author tag instead of replacing.

2022-04-29 10:00 UTC, rengaw83 commented on Classes/Middleware/SetVarnishHeadersMiddleware.php
> +        if (array_key_exists('INTincScript', $tsfe->config)) {
this means the header is only written if there is no int script,
but the header should be written with zero value if there are no intscripts.

2022-04-29 10:00 UTC, rengaw83 commented on Classes/Repository/CacheTagsRepository.php
> +    private string $tableName = 'tx_mkvarnish_cache_tags';
why we use a private property instead a constant now?
whats wrong with a private const?
but maybe this is unnecessary, we can use the table name directly instead of the const/property.

2022-04-29 10:00 UTC, rengaw83 commented on Classes/Utility/Configuration.php
> +            $this->extConf = \TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(
we should use use statements for namespaces here.

2022-04-29 10:00 UTC, rengaw83 commented on Configuration/RequestMiddlewares.php
> +                'typo3/cms-frontend/tsfe',
is this the right place?
isnt it better to put the middleware after `typo3/cms-frontend/prepare-tsfe-rendering`?

2022-04-29 10:00 UTC, rengaw83 commented on composer.json
> +        "nimut/testing-framework": "^1.1 || ^2.0 || ^3.0 || ^4.0 || ^5.0 || ^6.0",
we only support php 7.4 and 8.0. there is nosupport needed for old nimut versions, "^6.0" is enough. please check other dev requirements like phpunit too.

2022-04-29 10:00 UTC, rengaw83 commented on ext_emconf.php
> +    'version' => '11.0.0',
isn't released yet ;)

2022-04-29 10:03 UTC, rengaw83 commented on Classes/Middleware/SetVarnishHeadersMiddleware.php
> +        if (array_key_exists('INTincScript', $tsfe->config)) {
we can simply use null coalescing operator here:
`$headers['X-TYPO3-INTincScripts'] = count((array) ($tsfe->config['INTincScript'] ?? []));`

2022-04-29 12:28 UTC, rengaw83 commented on ext_emconf.php
> +            'typo3' => '11.5.0-11.5.99',
We do not support current and last elts anymore? only the latest elts? why?

2022-05-02 10:44 UTC, hannesbochmann commented on Configuration/RequestMiddlewares.php
> +                'typo3/cms-frontend/tsfe',
typo3/cms-frontend/prepare-tsfe-rendering is a internal Middleware which should not be referenced.

2022-05-02 11:34 UTC, hannesbochmann commented
This PR is based on the master and therefore will be dropped. Everything was now done directly in the 11.5 branch of the origin.

2022-05-02 11:35 UTC, closed without merging